newspaceProject/newspace-backend

build.gradle
src/main/java/com/lgcns/newspacebackend/domain/user/entity/User.java

feat : 유저 엔티티 생성, JWT 토큰 의존성 추가

feat : 유저 엔티티 생성, JWT 토큰 의존성 추가

---

src/main/java/com/lgcns/newspacebackend/domain/news/service/NewsService.java

model 변경
prompt 내용 한글->영어 변경
temperature 값 0.7 -> 0.5 변경

fix : prompt 정확도 및 속도 개선

---

src/main/java/com/lgcns/newspacebackend/domain/user/controller/UserController.java
src/main/java/com/lgcns/newspacebackend/domain/user/entity/User.java
src/main/java/com/lgcns/newspacebackend/domain/user/service/UserService.java

fix : UserController 수정

---

src/main/java/com/lgcns/newspacebackend/global/security/config/WebConfig.java

feat : cors 업데이트

---

src/main/java/com/lgcns/newspacebackend/domain/user/controller/UserController.java
src/main/java/com/lgcns/newspacebackend/domain/user/entity/User.java
src/main/java/com/lgcns/newspacebackend/domain/user/repository/UserRepository.java
src/main/java/com/lgcns/newspacebackend/domain/user/service/UserService.java
src/main/java/com/lgcns/newspacebackend/global/security/filter/JwtAuthenticationFilter.java

feat : MVC 구조 적용(logout, signout)

feat : MVC 구조 적용(logout, signout)

---

src/main/java/com/lgcns/newspacebackend/domain/user/controller/UserController.java
src/main/java/com/lgcns/newspacebackend/domain/user/service/UserService.java

refactor : UserController 코드 정리

---

src/main/java/com/lgcns/newspacebackend/domain/user/controller/UserController.java
src/main/java/com/lgcns/newspacebackend/domain/user/service/UserService.java
src/main/java/com/lgcns/newspacebackend/global/util/FileUtil.java

fix : 이미지 확장자 관련 수정

---

src/main/java/com/lgcns/newspacebackend/domain/user/controller/UserController.java
src/main/java/com/lgcns/newspacebackend/domain/user/service/UserService.java

fix : 프로필 이미지 로직 수정

---

src/main/java/com/lgcns/newspacebackend/domain/user/dto/UserInfoResponseDto.java
src/main/java/com/lgcns/newspacebackend/domain/user/service/UserService.java
src/main/java/com/lgcns/newspacebackend/global/security/config/WebConfig.java

feat : corsMapping 수정

---

src/main/java/com/lgcns/newspacebackend/global/security/jwt/JwtTokenUtil.java

feat : JwtTokenUtil 쿠키에 토큰 추가 기능 - setSecure 수정

feat : JwtTokenUtil 쿠키에 토큰 추가 기능 - setSecure 수정

---

src/main/java/com/lgcns/newspacebackend/global/security/config/WebConfig.java

feat : Origins 백엔드 포트 추가

---

src/main/java/com/lgcns/newspacebackend/global/security/config/SecurityConfig.java

feat : SecurityConfig - 필터체인 메서드 수정

feat : SecurityConfig - 필터체인 메서드 수정

---

src/main/java/com/lgcns/newspacebackend/global/security/config/CorsConfig.java
src/main/java/com/lgcns/newspacebackend/global/security/config/SecurityConfig.java
src/main/java/com/lgcns/newspacebackend/global/security/config/WebConfig.java

feat : fix Cors

---

src/main/java/com/lgcns/newspacebackend/domain/notice/dto/NoticeResponseDto.java
src/main/java/com/lgcns/newspacebackend/domain/user/controller/UserController.java
src/main/java/com/lgcns/newspacebackend/global/security/config/SecurityConfig.java
src/main/java/com/lgcns/newspacebackend/global/security/config/WebConfig.java

feat : 자바독스 수정중

---

build.gradle
src/main/java/com/lgcns/newspacebackend/domain/user/controller/UserController.java

feat : 유레카, 게이트웨이 관련 의존성 추가, 유저 컨트롤러 자바독스 작성

feat : 유레카, 게이트웨이 관련 의존성 추가, 유저 컨트롤러 자바독스 작성

---

build.gradle
src/main/java/com/lgcns/newspacebackend/domain/user/controller/UserController.java
src/main/java/com/lgcns/newspacebackend/domain/user/service/UserService.java

feat : 유저 컨트롤러 관련 스웨거 작성

---

build.gradle

feat : 액추에이터 스타터 의존성 추가

---

src/main/java/com/lgcns/newspacebackend/global/security/config/CorsConfig.java

feat : 유레카포트를 CORSconfig에 추가

---

src/main/java/com/lgcns/newspacebackend/global/security/config/CorsConfig.java

feat : AllowOrigin *로 변경 모든 경로 허용

feat : AllowOrigin *로 변경 모든 경로 허용

---

src/main/java/com/lgcns/newspacebackend/global/security/config/CorsConfig.java

feat : addAllowedOrinPatterns로 변경

feat : addAllowedOrinPatterns로 변경

---

src/main/java/com/lgcns/newspacebackend/global/security/config/SecurityConfig.java

feat : Preflight OPTIONS 설정

---

src/main/java/com/lgcns/newspacebackend/global/security/config/SecurityConfig.java

feat : aasdfsfdsfda

---

src/main/java/com/lgcns/newspacebackend/domain/news/service/NewsCategoryService.java
src/main/java/com/lgcns/newspacebackend/domain/news/service/NewsKeywordService.java
src/main/java/com/lgcns/newspacebackend/domain/notice/service/NoticeService.java
src/main/java/com/lgcns/newspacebackend/domain/user/controller/UserController.java
src/main/java/com/lgcns/newspacebackend/domain/user/service/UserService.java
src/main/java/com/lgcns/newspacebackend/global/exception/BaseException.java
src/main/java/com/lgcns/newspacebackend/global/exception/BaseResponseStatus.java
src/main/java/com/lgcns/newspacebackend/global/security/UserDetailsServiceImpl.java
src/main/java/com/lgcns/newspacebackend/global/security/filter/JwtAuthenticationFilter.java
src/main/java/com/lgcns/newspacebackend/global/security/filter/JwtAuthorizationFilter.java
src/main/java/com/lgcns/newspacebackend/global/security/jwt/JwtTokenUtil.java
src/main/java/com/lgcns/newspacebackend/global/security/util/FilterResponseUtil.java

BaseException, BaseResponseStatus 추가 및 적용
불필요 주석 제거
transactional 어노테이션 누락 수정 등

feat : 예외처리 커스텀 추가 및 코드 전체 다듬기
